AWSTemplateFormatVersion: 2010-09-09

Description:  | 
  Kittens Carousel is a static website application deployed with Apache Web Server on AWS Elastic 
  Compute Cloud (EC2) Instance using AWS Cloudformation Service.

Resources:
  HakanCFInstance: 
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0a8b4cd432b1c3063
      InstanceType: t2.micro
      KeyName: my.key
      SecurityGroups:
        - first-try
      Tags:
        - Key: Name
          Value: Web server of Kittens Carousel
      UserData:
        Fn::Base64:
          !Sub |
          #! /bin/bash
          sudo yum update
          sudo yum install httpd -y
          sudo systemctl start httpd
          sudo systemctl enable httpd
          sudo chmod -R 777 var/www/html
          cd var/www/html
          wget https://raw.githubusercontent.com/hkn-asln/my-projects/main/aws/projects/Project-101-kittens-carousel-static-website-ec2/static-web/index.html
          wget https://raw.githubusercontent.com/hkn-asln/my-projects/main/aws/projects/Project-101-kittens-carousel-static-website-ec2/static-web/cat0.jpg
          wget https://raw.githubusercontent.com/hkn-asln/my-projects/main/aws/projects/Project-101-kittens-carousel-static-website-ec2/static-web/cat1.jpg
          wget https://raw.githubusercontent.com/hkn-asln/my-projects/main/aws/projects/Project-101-kittens-carousel-static-website-ec2/static-web/cat2.jpg
          
          
          